version: "3.5"

services: 

    portfolio:
        container_name: docker-react
        hostname: docker-react
        restart: always
        build: 
          context: .
          dockerfile: Dockerfile-react 
        command: npm run start
        networks:
            - default
        ports:
            - '3001:3001'
        volumes:
            - .:/usr/src/portfolio

#     app:
#         container_name: server-side
#         hostname: server-side
#         restart: always
#         build: .
#         command: nodemon /usr/src/app/server/index.js 
#         networks:
#             - default
#         ports:
#             - '3000:3000'
#         volumes:
#             - .:/usr/src/app/
#         depends_on: 
#             - mongo
      
#     mongo:
#         image: mongo:latest
#         container_name: mongo
#         hostname: mongo
#         #command: mongod --port 27018
#         networks:
#           - default
#         volumes: 
#           - data:/data/db
#         ports:
#           - "27017:27017"
#         expose:
#           - "27017"

# networks:
#     default:
#         driver: bridge


# volumes:
#     data: 